"""auto_migration

Revision ID: 8953e00c346a
Revises: 
Create Date: 2026-03-18 04:31:10.438789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8953e00c346a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_path', 'audit_log', ['path'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['username'], unique=False)
    op.drop_index(op.f('idx_snapshots_detector'), table_name='idea_snapshots')
    op.drop_index(op.f('idx_snapshots_eval_status'), table_name='idea_snapshots')
    op.drop_index(op.f('idx_snapshots_ticker_date'), table_name='idea_snapshots')
    op.drop_index(op.f('ix_idea_snapshots_generated_at'), table_name='idea_snapshots')
    op.drop_index(op.f('ix_idea_snapshots_snapshot_id'), table_name='idea_snapshots')
    op.drop_index(op.f('ix_idea_snapshots_ticker'), table_name='idea_snapshots')
    op.drop_table('idea_snapshots')
    op.drop_index(op.f('idx_dsm_dataset_ticker'), table_name='research_dataset_members')
    op.drop_table('research_dataset_members')
    op.drop_index(op.f('idx_research_ds_name_ver'), table_name='research_datasets')
    op.drop_index(op.f('ix_research_datasets_dataset_id'), table_name='research_datasets')
    op.drop_table('research_datasets')
    op.drop_index(op.f('idx_sig_hist_category'), table_name='signal_history')
    op.drop_index(op.f('idx_sig_hist_signal'), table_name='signal_history')
    op.drop_index(op.f('idx_sig_hist_ticker_date'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_signal_id'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_ticker'), table_name='signal_history')
    op.drop_table('signal_history')
    op.drop_index(op.f('idx_feat_snap_set'), table_name='feature_snapshots')
    op.drop_index(op.f('idx_feat_snap_ticker_date'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_ticker'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('idx_outcomes_detector'), table_name='snapshot_outcomes')
    op.drop_index(op.f('idx_outcomes_snapshot'), table_name='snapshot_outcomes')
    op.drop_index(op.f('ix_snapshot_outcomes_snapshot_id'), table_name='snapshot_outcomes')
    op.drop_table('snapshot_outcomes')
    op.add_column('opportunity_performance', sa.Column('case_score', sa.Float(), nullable=True))
    op.add_column('opportunity_performance', sa.Column('fundamental_score', sa.Float(), nullable=True))
    op.add_column('opportunity_performance', sa.Column('technical_score', sa.Float(), nullable=True))
    op.alter_column('signal_activations', 'is_expired',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('strategies', sa.Column('version', sa.String(length=20), nullable=True))
    op.add_column('strategies', sa.Column('lifecycle_state', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'lifecycle_state')
    op.drop_column('strategies', 'version')
    op.alter_column('signal_activations', 'is_expired',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('opportunity_performance', 'technical_score')
    op.drop_column('opportunity_performance', 'fundamental_score')
    op.drop_column('opportunity_performance', 'case_score')
    op.create_table('snapshot_outcomes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('horizon', sa.VARCHAR(length=5), nullable=False),
    sa.Column('evaluated_at', sa.DATETIME(), nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=16), nullable=False),
    sa.Column('detector', sa.VARCHAR(length=30), nullable=False),
    sa.Column('idea_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('signal_strength', sa.FLOAT(), nullable=True),
    sa.Column('alpha_score', sa.FLOAT(), nullable=True),
    sa.Column('price_at_signal', sa.FLOAT(), nullable=True),
    sa.Column('price_at_horizon', sa.FLOAT(), nullable=True),
    sa.Column('raw_return', sa.FLOAT(), nullable=True),
    sa.Column('excess_return', sa.FLOAT(), nullable=True),
    sa.Column('max_favorable_excursion', sa.FLOAT(), nullable=True),
    sa.Column('max_adverse_excursion', sa.FLOAT(), nullable=True),
    sa.Column('drawdown_from_signal', sa.FLOAT(), nullable=True),
    sa.Column('is_hit', sa.BOOLEAN(), nullable=True),
    sa.Column('outcome_label', sa.VARCHAR(length=10), nullable=True),
    sa.Column('data_available', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_outcomes_snapshot_id'), 'snapshot_outcomes', ['snapshot_id'], unique=False)
    op.create_index(op.f('idx_outcomes_snapshot'), 'snapshot_outcomes', ['snapshot_id', 'horizon'], unique=False)
    op.create_index(op.f('idx_outcomes_detector'), 'snapshot_outcomes', ['detector', 'horizon', 'outcome_label'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=16), nullable=False),
    sa.Column('snapshot_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('feature_set', sa.VARCHAR(length=50), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('features_json', sa.TEXT(), nullable=False),
    sa.Column('source_versions_json', sa.TEXT(), nullable=True),
    sa.Column('row_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_snapshots_ticker'), 'feature_snapshots', ['ticker'], unique=False)
    op.create_index(op.f('idx_feat_snap_ticker_date'), 'feature_snapshots', ['ticker', 'snapshot_date', 'feature_set'], unique=False)
    op.create_index(op.f('idx_feat_snap_set'), 'feature_snapshots', ['feature_set', 'snapshot_date'], unique=False)
    op.create_table('signal_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('signal_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=16), nullable=False),
    sa.Column('fire_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('strength', sa.VARCHAR(length=10), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('direction', sa.VARCHAR(length=10), nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('decay_factor', sa.FLOAT(), nullable=True),
    sa.Column('half_life_days', sa.FLOAT(), nullable=True),
    sa.Column('price_at_fire', sa.FLOAT(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_history_ticker'), 'signal_history', ['ticker'], unique=False)
    op.create_index(op.f('ix_signal_history_signal_id'), 'signal_history', ['signal_id'], unique=False)
    op.create_index(op.f('idx_sig_hist_ticker_date'), 'signal_history', ['ticker', 'fire_date'], unique=False)
    op.create_index(op.f('idx_sig_hist_signal'), 'signal_history', ['signal_id', 'fire_date'], unique=False)
    op.create_index(op.f('idx_sig_hist_category'), 'signal_history', ['category', 'fire_date'], unique=False)
    op.create_table('research_datasets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tickers_json', sa.TEXT(), nullable=False),
    sa.Column('date_start', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_end', sa.VARCHAR(length=10), nullable=False),
    sa.Column('feature_sets_json', sa.TEXT(), nullable=True),
    sa.Column('signals_json', sa.TEXT(), nullable=True),
    sa.Column('ticker_count', sa.INTEGER(), nullable=True),
    sa.Column('row_count', sa.INTEGER(), nullable=True),
    sa.Column('tags_json', sa.TEXT(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_datasets_dataset_id'), 'research_datasets', ['dataset_id'], unique=1)
    op.create_index(op.f('idx_research_ds_name_ver'), 'research_datasets', ['name', 'version'], unique=False)
    op.create_table('research_dataset_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=16), nullable=False),
    sa.Column('sector', sa.VARCHAR(length=100), nullable=True),
    sa.Column('market_cap', sa.FLOAT(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['research_datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_dsm_dataset_ticker'), 'research_dataset_members', ['dataset_id', 'ticker'], unique=False)
    op.create_table('idea_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('scan_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=16), nullable=False),
    sa.Column('detector', sa.VARCHAR(length=30), nullable=False),
    sa.Column('idea_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), nullable=True),
    sa.Column('signal_strength', sa.FLOAT(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('alpha_score', sa.FLOAT(), nullable=True),
    sa.Column('rank_score', sa.FLOAT(), nullable=True),
    sa.Column('active_signals_count', sa.INTEGER(), nullable=True),
    sa.Column('strong_signals_count', sa.INTEGER(), nullable=True),
    sa.Column('moderate_signals_count', sa.INTEGER(), nullable=True),
    sa.Column('weak_signals_count', sa.INTEGER(), nullable=True),
    sa.Column('rationale', sa.TEXT(), nullable=True),
    sa.Column('scan_mode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('strategy_profile', sa.VARCHAR(length=50), nullable=True),
    sa.Column('registry_key', sa.VARCHAR(length=30), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), nullable=True),
    sa.Column('confidence_level', sa.VARCHAR(length=10), nullable=True),
    sa.Column('price_at_signal', sa.FLOAT(), nullable=True),
    sa.Column('market_metadata_json', sa.TEXT(), nullable=True),
    sa.Column('evaluation_status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_snapshots_ticker'), 'idea_snapshots', ['ticker'], unique=False)
    op.create_index(op.f('ix_idea_snapshots_snapshot_id'), 'idea_snapshots', ['snapshot_id'], unique=1)
    op.create_index(op.f('ix_idea_snapshots_generated_at'), 'idea_snapshots', ['generated_at'], unique=False)
    op.create_index(op.f('idx_snapshots_ticker_date'), 'idea_snapshots', ['ticker', 'generated_at'], unique=False)
    op.create_index(op.f('idx_snapshots_eval_status'), 'idea_snapshots', ['evaluation_status', 'generated_at'], unique=False)
    op.create_index(op.f('idx_snapshots_detector'), 'idea_snapshots', ['detector', 'idea_type', 'generated_at'], unique=False)
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_path', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
