"""
src/data/models/portfolio.py
─────────────────────────────────────────────────────────────────────────────
Portfolio, position, and idea models.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, Integer, Float, String, Text, DateTime,
    Index, ForeignKey,
)
from sqlalchemy.orm import relationship

from src.data.models.base import Base


class Portfolio(Base):
    __tablename__ = "portfolios"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    name             = Column(String(100), nullable=False)
    strategy         = Column(String(100))
    risk_level       = Column(String(50))
    total_allocation = Column(Float)
    created_at       = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    positions        = relationship("PortfolioPosition", back_populates="portfolio", cascade="all, delete-orphan")


class PortfolioPosition(Base):
    __tablename__ = "portfolio_positions"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    portfolio_id     = Column(Integer, ForeignKey("portfolios.id"), nullable=False, index=True)
    ticker           = Column(String(16), nullable=False)
    target_weight    = Column(Float, nullable=False)
    role             = Column(String(20))
    sector           = Column(String(100))
    volatility_atr   = Column(Float)

    portfolio        = relationship("Portfolio", back_populates="positions")


class IdeaRecord(Base):
    """Persisted investment idea generated by the Idea Generation Engine."""
    __tablename__ = "ideas"
    __table_args__ = (
        Index("idx_ideas_status_priority", "status", "priority"),
        Index("idx_ideas_ticker", "ticker", "generated_at"),
    )

    id               = Column(Integer, primary_key=True, autoincrement=True)
    idea_uid         = Column(String(16), nullable=False, unique=True)
    ticker           = Column(String(16), nullable=False, index=True)
    name             = Column(String(200), default="")
    sector           = Column(String(100), default="")
    idea_type        = Column(String(20), nullable=False)
    confidence       = Column(String(10), nullable=False)
    signal_strength  = Column(Float, nullable=False)
    priority         = Column(Integer, nullable=False, default=0)
    signals_json     = Column(Text, nullable=False)
    status           = Column(String(20), default="active")
    generated_at     = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    expires_at       = Column(DateTime)
    analyzed_at      = Column(DateTime)
    metadata_json    = Column(Text, default="{}")


class OpportunityAlertRecord(Base):
    """Persistent store for opportunity monitoring alerts."""
    __tablename__ = "opportunity_alerts"
    __table_args__ = (
        Index("idx_opp_alerts_ticker", "ticker", "created_at"),
        Index("idx_opp_alerts_severity", "severity", "read", "created_at"),
    )

    id          = Column(String(64), primary_key=True)
    ticker      = Column(String(16), nullable=False, index=True)
    alert_type  = Column(String(30), nullable=False)
    severity    = Column(String(20), nullable=False)
    title       = Column(String(200))
    description = Column(Text)
    prev_value  = Column(Float)
    curr_value  = Column(Float)
    delta       = Column(Float)
    new_signals = Column(Text)
    created_at  = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    read        = Column(Boolean, default=False)
