"""
src/engines/super_alpha/models.py
──────────────────────────────────────────────────────────────────────────────
Shared Pydantic data contracts for the Super Alpha Engine.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ── Enums ─────────────────────────────────────────────────────────────────────

class FactorName(str, Enum):
    VALUE = "value"
    MOMENTUM = "momentum"
    QUALITY = "quality"
    SIZE = "size"
    VOLATILITY = "volatility"
    SENTIMENT = "sentiment"
    MACRO = "macro"
    EVENT = "event"


class AlphaTier(str, Enum):
    """Composite score tier classification."""
    ALPHA_ELITE = "Alpha Elite"      # ≥ 85
    STRONG_ALPHA = "Strong Alpha"    # ≥ 70
    MODERATE_ALPHA = "Moderate Alpha" # ≥ 55
    NEUTRAL = "Neutral"               # ≥ 40
    WEAK = "Weak"                     # ≥ 25
    AVOID = "Avoid"                   # < 25


class AlertType(str, Enum):
    TOP_PERCENTILE = "top_percentile"
    SENTIMENT_SHIFT = "sentiment_shift"
    CORPORATE_EVENT = "corporate_event"
    MACRO_REGIME_CHANGE = "macro_regime_change"
    VOLATILITY_SPIKE = "volatility_spike"
    FACTOR_CONVERGENCE = "factor_convergence"


# ── Factor Score ──────────────────────────────────────────────────────────────

class VariableContribution(BaseModel):
    """Single variable's contribution to a factor score."""
    name: str
    raw_value: float | None = None
    z_score: float | None = None
    weight: float = 0.0
    weighted_contribution: float = 0.0


class FactorScore(BaseModel):
    """Generic 0–100 factor score with full explainability."""
    factor: FactorName
    score: float = Field(0.0, ge=0, le=100)
    percentile: float | None = None
    variables: list[VariableContribution] = Field(default_factory=list)
    signals: list[str] = Field(default_factory=list)
    data_quality: float = Field(1.0, ge=0, le=1, description="Fraction of variables with data")


# ── Composite Profile ────────────────────────────────────────────────────────

class CompositeAlphaProfile(BaseModel):
    """Full 8-factor profile for a single asset."""
    ticker: str
    composite_alpha_score: float = Field(0.0, ge=0, le=100)
    tier: AlphaTier = AlphaTier.NEUTRAL
    rank: int | None = None
    percentile: float | None = None

    # Individual factor scores
    value: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.VALUE))
    momentum: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.MOMENTUM))
    quality: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.QUALITY))
    size: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.SIZE))
    volatility: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.VOLATILITY))
    sentiment: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.SENTIMENT))
    macro: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.MACRO))
    event: FactorScore = Field(default_factory=lambda: FactorScore(factor=FactorName.EVENT))

    # Explainability
    convergence_bonus: float = 0.0
    volatility_adjustment: float = 0.0
    factor_agreement: int = 0
    top_drivers: list[str] = Field(default_factory=list)

    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class FactorExposure(BaseModel):
    """Radar-chart-ready factor exposure map."""
    ticker: str
    exposures: dict[str, float] = Field(default_factory=dict)


# ── Ranking ───────────────────────────────────────────────────────────────────

class SuperAlphaRanking(BaseModel):
    """Ranked universe of assets."""
    rankings: list[CompositeAlphaProfile] = Field(default_factory=list)
    universe_size: int = 0
    top_alpha: list[str] = Field(default_factory=list)
    bottom_alpha: list[str] = Field(default_factory=list)
    market_regime: str = "unknown"
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ── Alerts ────────────────────────────────────────────────────────────────────

class SuperAlphaAlert(BaseModel):
    """Alert generated by the Super Alpha system."""
    alert_type: AlertType
    ticker: str | None = None
    severity: str = "moderate"  # low, moderate, high, critical
    headline: str = ""
    detail: str = ""
    factor_scores: dict[str, float] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SuperAlphaDashboard(BaseModel):
    """Executive dashboard payload."""
    ranking: SuperAlphaRanking = Field(default_factory=SuperAlphaRanking)
    alerts: list[SuperAlphaAlert] = Field(default_factory=list)
    regime_summary: dict[str, Any] = Field(default_factory=dict)
    factor_heatmap: list[FactorExposure] = Field(default_factory=list)
