"""
src/engines/idea_generation/backtest/__init__.py
──────────────────────────────────────────────────────────────────────────────
IDEA Backtesting + Calibration Layer.

Provides ex-post evaluation, analytics, calibration, and alpha decay
analysis for ideas generated by the Idea Generation Engine.
"""

from src.engines.idea_generation.backtest.models import (
    EvaluationHorizon,
    OutcomeLabel,
    HitPolicy,
    BacktestConfig,
    IdeaSnapshot,
    OutcomeResult,
)

__all__ = [
    "EvaluationHorizon",
    "OutcomeLabel",
    "HitPolicy",
    "BacktestConfig",
    "IdeaSnapshot",
    "OutcomeResult",
]
