"""
src/engines/opportunity_tracking/__init__.py
──────────────────────────────────────────────────────────────────────────────
Opportunity Performance Tracking module.

Tracks forward P&L of ideas generated by the Idea Generation Engine
to empirically measure detector accuracy and system effectiveness.
"""

from src.engines.opportunity_tracking.models import (
    DetectorAccuracy,
    OpportunityPerformanceSummary,
)
from src.engines.opportunity_tracking.tracker import OpportunityTracker

__all__ = [
    "DetectorAccuracy",
    "OpportunityPerformanceSummary",
    "OpportunityTracker",
]
