"""
src/engines/opportunity_tracking/tracker.py
──────────────────────────────────────────────────────────────────────────────
Opportunity Performance Tracker.

Registers ideas from the Idea Generation Engine, updates forward returns
asynchronously, and computes aggregate detector accuracy statistics.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime, timedelta, timezone

import numpy as np
import yfinance as yf

from src.engines.idea_generation.models import IdeaCandidate
from src.engines.opportunity_tracking.models import (
    DetectorAccuracy,
    OpportunityPerformanceSummary,
)
from src.engines.opportunity_tracking.repository import OpportunityRepository

logger = logging.getLogger("365advisers.opportunity_tracking.tracker")

# Forward return windows in calendar days
_RETURN_WINDOWS = {
    "return_1d": 1,
    "return_5d": 5,
    "return_20d": 20,
    "return_60d": 60,
}

_TRADING_DAYS_YEAR = 252
_REF_WINDOW = 20


class OpportunityTracker:
    """
    Tracks forward performance of ideas generated by the IGE.

    Usage::

        tracker = OpportunityTracker()
        tracker.register_idea(idea, opp_score=72.5, suggested_alloc=8.5)
        await tracker.update_returns()
        summary = tracker.get_performance_summary()
    """

    def __init__(self) -> None:
        self._repo = OpportunityRepository

    # ── Registration ──────────────────────────────────────────────────────

    def register_idea(
        self,
        idea: IdeaCandidate,
        opp_score: float | None = None,
        suggested_alloc: float | None = None,
    ) -> int:
        """
        Record a new idea with its price at generation time.

        Parameters
        ----------
        idea : IdeaCandidate
            The idea from the Idea Generation Engine.
        opp_score : float | None
            Unified Opportunity Score at generation time.
        suggested_alloc : float | None
            Suggested allocation percentage.

        Returns
        -------
        int
            The persisted record ID.
        """
        # Fetch current price for the ticker
        price = self._fetch_current_price(idea.ticker)

        record_id = self._repo.save_opportunity(
            idea_uid=idea.id,
            ticker=idea.ticker,
            idea_type=idea.idea_type.value,
            confidence=idea.confidence.value,
            signal_strength=idea.signal_strength,
            price_at_gen=price,
            generated_at=idea.generated_at,
            opportunity_score=opp_score,
            suggested_alloc=suggested_alloc,
        )

        logger.info(
            "OPP-TRACKER: Registered idea %s (%s, %s) @ $%.2f",
            idea.id, idea.ticker, idea.idea_type.value, price,
        )
        return record_id

    # ── Async Return Updates ──────────────────────────────────────────────

    async def update_returns(self, max_age_days: int = 90) -> int:
        """
        Batch update forward returns for all tracked ideas.

        Fetches current prices and computes returns relative to
        original price_at_gen. Idempotent — safe to call repeatedly.

        Returns
        -------
        int
            Number of records updated.
        """
        pending = self._repo.get_pending_updates(max_age_days)
        if not pending:
            return 0

        updated = 0
        now = datetime.now(timezone.utc)

        # Group by ticker for batch price fetch
        tickers = list({r.ticker for r in pending})
        prices = self._fetch_batch_prices(tickers)

        for record in pending:
            if record.price_at_gen is None or record.price_at_gen <= 0:
                continue

            current_price = prices.get(record.ticker)
            if current_price is None:
                continue

            age_days = (now - record.generated_at).days
            gen_price = record.price_at_gen

            # Compute available returns based on idea age
            updates: dict[str, float | None] = {}
            benchmark_price = prices.get("SPY")

            for field, days in _RETURN_WINDOWS.items():
                if age_days >= days:
                    # Simple return approximation using current price
                    # In production, historical close at T+N would be used
                    ret = (current_price - gen_price) / gen_price
                    updates[field] = round(ret, 6)

            if not updates:
                continue

            # Determine tracking status
            if age_days >= 60:
                status = "complete"
            elif age_days >= 20:
                status = "partial"
            else:
                status = "pending"

            # Compute benchmark excess for T+20
            benchmark_ret = None
            excess_ret = None
            if "return_20d" in updates and benchmark_price is not None:
                # Simplified: in production, compute from historical SPY
                benchmark_ret = 0.0  # Would be filled by actual benchmark data
                excess_ret = updates.get("return_20d", 0.0)

            self._repo.update_returns(
                idea_uid=record.idea_uid,
                return_1d=updates.get("return_1d"),
                return_5d=updates.get("return_5d"),
                return_20d=updates.get("return_20d"),
                return_60d=updates.get("return_60d"),
                benchmark_return_20d=benchmark_ret,
                excess_return_20d=excess_ret,
                tracking_status=status,
            )
            updated += 1

        logger.info("OPP-TRACKER: Updated returns for %d / %d ideas", updated, len(pending))
        return updated

    # ── Performance Summaries ─────────────────────────────────────────────

    def get_performance_summary(
        self,
        idea_type: str | None = None,
        min_age_days: int = 20,
    ) -> OpportunityPerformanceSummary:
        """
        Aggregate statistics: hit rate, avg return, by detector type.

        Parameters
        ----------
        idea_type : str | None
            Filter by detector type (value, momentum, etc.)
        min_age_days : int
            Minimum age for inclusion (default 20 trading days).
        """
        records = self._repo.get_by_type(idea_type, min_age_days)
        total = self._repo.count_all()
        complete = [r for r in records if r.return_20d is not None]

        if not complete:
            return OpportunityPerformanceSummary(
                total_ideas=total,
                total_tracked=len(records),
            )

        # Aggregate metrics
        returns_20d = [r.return_20d for r in complete if r.return_20d is not None]
        excess_20d = [r.excess_return_20d for r in complete if r.excess_return_20d is not None]

        hit_rate = sum(1 for r in returns_20d if r > 0) / len(returns_20d) if returns_20d else 0.0
        avg_ret = sum(returns_20d) / len(returns_20d) if returns_20d else 0.0
        avg_excess = sum(excess_20d) / len(excess_20d) if excess_20d else 0.0

        # Best / worst
        best_rec = max(complete, key=lambda r: r.return_20d or 0)
        worst_rec = min(complete, key=lambda r: r.return_20d or 0)

        # By type
        by_type = self._group_accuracy(complete, key_fn=lambda r: r.idea_type)

        # By confidence
        by_conf = self._group_accuracy(complete, key_fn=lambda r: r.confidence)

        return OpportunityPerformanceSummary(
            total_ideas=total,
            total_tracked=len(records),
            total_complete=len(complete),
            hit_rate_20d=round(hit_rate, 4),
            avg_return_20d=round(avg_ret, 6),
            avg_excess_return_20d=round(avg_excess, 6),
            best_idea=f"{best_rec.ticker} ({best_rec.idea_type})",
            worst_idea=f"{worst_rec.ticker} ({worst_rec.idea_type})",
            by_type=by_type,
            by_confidence=by_conf,
        )

    def get_detector_accuracy(self) -> dict[str, DetectorAccuracy]:
        """Per-detector precision: what % of ideas generated positive returns."""
        records = self._repo.get_all_complete(min_age_days=20)
        return self._group_accuracy(records, key_fn=lambda r: r.idea_type)

    # ── Private Helpers ───────────────────────────────────────────────────

    @staticmethod
    def _group_accuracy(records, key_fn) -> dict[str, DetectorAccuracy]:
        """Group records and compute accuracy per group."""
        groups: dict[str, list] = defaultdict(list)
        for r in records:
            groups[key_fn(r)].append(r)

        result: dict[str, DetectorAccuracy] = {}
        for label, group in groups.items():
            returns = [r.return_20d for r in group if r.return_20d is not None]
            excess = [r.excess_return_20d for r in group if r.excess_return_20d is not None]

            hit_rate = sum(1 for r in returns if r > 0) / len(returns) if returns else 0.0
            avg_ret = sum(returns) / len(returns) if returns else 0.0
            avg_exc = sum(excess) / len(excess) if excess else 0.0

            # Sharpe approximation
            sharpe = 0.0
            if len(returns) >= 5:
                arr = np.array(returns)
                std = float(np.std(arr, ddof=1))
                if std > 1e-9:
                    annualisation = (_TRADING_DAYS_YEAR / _REF_WINDOW) ** 0.5
                    sharpe = round((float(np.mean(arr)) / std) * annualisation, 4)

            result[label] = DetectorAccuracy(
                label=label,
                idea_count=len(group),
                hit_rate=round(hit_rate, 4),
                avg_return=round(avg_ret, 6),
                avg_excess_return=round(avg_exc, 6),
                sharpe=sharpe,
            )

        return result

    @staticmethod
    def _fetch_current_price(ticker: str) -> float:
        """Fetch the latest close price for a single ticker."""
        try:
            tk = yf.Ticker(ticker)
            hist = tk.history(period="2d")
            if hist is not None and not hist.empty:
                return float(hist["Close"].iloc[-1])
        except Exception as exc:
            logger.warning("OPP-TRACKER: Failed to fetch price for %s — %s", ticker, exc)
        return 0.0

    @staticmethod
    def _fetch_batch_prices(tickers: list[str]) -> dict[str, float]:
        """Fetch latest close prices for multiple tickers."""
        prices: dict[str, float] = {}
        try:
            # Include SPY for benchmark
            all_tickers = list(set(tickers + ["SPY"]))
            data = yf.download(all_tickers, period="2d", progress=False, auto_adjust=True)
            if data is not None and not data.empty:
                close = data["Close"] if "Close" in data.columns else data
                if isinstance(close, pd.Series):
                    # Single ticker
                    prices[all_tickers[0]] = float(close.iloc[-1])
                else:
                    for t in all_tickers:
                        if t in close.columns:
                            val = close[t].iloc[-1]
                            if not np.isnan(val):
                                prices[t] = float(val)
        except Exception as exc:
            logger.warning("OPP-TRACKER: Batch price fetch failed — %s", exc)
        return prices


# Lazy import to avoid circular dependency
import pandas as pd  # noqa: E402
