"""
src/engines/event_backtester/models.py — Event-driven backtester contracts.
"""
from __future__ import annotations
from datetime import datetime, timezone
from enum import Enum
from pydantic import BaseModel, Field


class EventType(str, Enum):
    MARKET = "market"
    SIGNAL = "signal"
    ORDER = "order"
    FILL = "fill"


class MarketEvent(BaseModel):
    """Tick-level market data event."""
    event_type: EventType = EventType.MARKET
    timestamp: datetime
    ticker: str
    price: float
    volume: int = 0
    bid: float = 0.0
    ask: float = 0.0


class SignalEvent(BaseModel):
    """Trading signal generated by strategy."""
    event_type: EventType = EventType.SIGNAL
    timestamp: datetime
    ticker: str
    signal: float  # -1.0 (short) to +1.0 (long)
    strategy_id: str = ""


class OrderEvent(BaseModel):
    """Order to be executed."""
    event_type: EventType = EventType.ORDER
    timestamp: datetime
    ticker: str
    side: str  # buy | sell
    quantity: float
    order_type: str = "market"
    limit_price: float | None = None


class FillEvent(BaseModel):
    """Execution fill with slippage and commission."""
    event_type: EventType = EventType.FILL
    timestamp: datetime
    ticker: str
    side: str
    quantity: float
    fill_price: float
    commission: float = 0.0
    slippage: float = 0.0


class TradeLog(BaseModel):
    """Individual trade record."""
    entry_time: datetime
    exit_time: datetime | None = None
    ticker: str
    side: str
    quantity: float
    entry_price: float
    exit_price: float = 0.0
    pnl: float = 0.0
    commission: float = 0.0
    holding_period: int = 0  # bars


class BacktestConfig(BaseModel):
    initial_capital: float = 1_000_000.0
    commission_bps: float = 5.0  # basis points per trade
    slippage_bps: float = 5.0
    max_position_pct: float = 0.10  # max 10% per position
    enable_shorting: bool = True


class BacktestResult(BaseModel):
    total_return: float = 0.0
    annualised_return: float = 0.0
    volatility: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    total_trades: int = 0
    avg_trade_pnl: float = 0.0
    final_equity: float = 0.0
    equity_curve: list[float] = Field(default_factory=list)
    trade_log: list[TradeLog] = Field(default_factory=list)
    events_processed: int = 0
