"""
src/engines/stat_arb/models.py
──────────────────────────────────────────────────────────────────────────────
Pydantic data contracts for the Statistical Arbitrage / Pairs Trading subsystem.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field


# ── Enumerations ─────────────────────────────────────────────────────────────

class ZScoreSignal(str, Enum):
    """Trading signal generated by z-score analysis."""
    LONG_A_SHORT_B = "long_a_short_b"   # Spread is below -entry → buy A, sell B
    LONG_B_SHORT_A = "long_b_short_a"   # Spread is above +entry → buy B, sell A
    NEUTRAL = "neutral"                  # No signal
    EXIT = "exit"                        # Spread returned to mean → close position


class PairStatus(str, Enum):
    """Current status of a tracked pair."""
    ACTIVE = "active"
    MONITORING = "monitoring"
    DEGRADED = "degraded"
    EXPIRED = "expired"


# ── Cointegration Result ─────────────────────────────────────────────────────

class CointegrationResult(BaseModel):
    """Result of an Engle-Granger cointegration test."""
    ticker_a: str
    ticker_b: str
    test_statistic: float = Field(description="ADF test statistic on residuals")
    p_value: float = Field(ge=0.0, le=1.0, description="ADF p-value")
    critical_values: dict[str, float] = Field(
        default_factory=dict,
        description="Critical values at 1%, 5%, 10% significance levels",
    )
    is_cointegrated: bool = Field(
        False,
        description="True if p_value < significance level (default 0.05)",
    )
    hedge_ratio: float = Field(
        1.0,
        description="OLS beta coefficient (regression slope A on B)",
    )
    half_life: float | None = Field(
        None, ge=0.0,
        description="Mean-reversion half-life in trading days",
    )
    residual_std: float = Field(0.0, ge=0.0)
    observations: int = 0


# ── Pair Candidate ───────────────────────────────────────────────────────────

class PairCandidate(BaseModel):
    """A candidate pair for stat-arb trading."""
    ticker_a: str
    ticker_b: str
    sector: str = "Unknown"
    correlation: float = Field(0.0, ge=-1.0, le=1.0)
    cointegration: CointegrationResult | None = None
    half_life: float | None = Field(None, ge=0.0)
    current_z_score: float | None = None
    current_signal: ZScoreSignal = ZScoreSignal.NEUTRAL
    spread_mean: float = 0.0
    spread_std: float = Field(0.0, ge=0.0)
    status: PairStatus = PairStatus.MONITORING
    quality_score: float = Field(
        0.0, ge=0.0, le=100.0,
        description="Composite quality: lower half-life + stronger cointegration = better",
    )
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ── Pair Spread Snapshot ─────────────────────────────────────────────────────

class PairSpread(BaseModel):
    """Single data point in a pair's spread time series."""
    date: datetime
    price_a: float
    price_b: float
    spread_value: float
    z_score: float
    signal: ZScoreSignal = ZScoreSignal.NEUTRAL


# ── Scan Result ──────────────────────────────────────────────────────────────

class PairScanResult(BaseModel):
    """Output of a universe-level pair scan."""
    pairs: list[PairCandidate] = Field(default_factory=list)
    universe_size: int = 0
    pairs_tested: int = 0
    pairs_cointegrated: int = 0
    scan_duration_ms: float = 0.0
    filters_applied: dict[str, float] = Field(default_factory=dict)
    scanned_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
